#
# This file has been automatically generated by the WICED 20719-B1 Designer.
#

APP_SRC = Zenitron_BT_AMP.c
APP_SRC += Zenitron_BT_AMP_sdp_db.c
APP_SRC += wiced_bt_cfg.c
APP_SRC += a2dp_sink.c
APP_SRC += a2dp_cfg.c
APP_SRC += wiced_platform_pin_config.c

$(NAME)_COMPONENTS   := a2dp_sink_profile.a

ifneq ($(CHIP), 43012)

ifeq ($(CHIP), 20703)
APP_PATCHES_AND_LIBS += wiced_audio_sink.a
else
#By default external Codec support is disabled in SDK
#Required libraries for external codec support is not available in this version of the SDK.
A2DP_EXT_CODEC=0

ifeq ($(A2DP_EXT_CODEC),1)
APP_PATCHES_AND_LIBS +=wiced_audio_sink_ext_lib.a
$(NAME)_COMPONENTS += AAC_codec_lib.a
else
APP_PATCHES_AND_LIBS += wiced_audio_sink_lib.a
endif
endif

endif

C_FLAGS += -DWICED_BT_TRACE_ENABLE

# If defined, HCI traces are sent over transport/WICED HCI interface
C_FLAGS += -DHCI_TRACE_OVER_TRANSPORT

C_FLAGS += -DA2DP_SINK_ENABLE_CONTENT_PROTECTION # Enables the content protection. Supports SCMS-T
ifneq ($(CHIP), 43012)
#C_FLAGS += -DWICED_COEX_ENABLE
endif

#AAC Passthrough flags. AAC Data can be routed either to the app or to the transport.
#C_FLAGS += -DA2DP_SINK_AAC_ENABLED

#Enable this flag, if external codec library is included
ifeq ($(A2DP_EXT_CODEC),1)
C_FLAGS += -DWICED_A2DP_EXT_CODEC=1
else
C_FLAGS += -DWICED_A2DP_EXT_CODEC=0
endif

###### define module type ######
C_FLAGS += -DCYBT423028=1
C_FLAGS += -DCY20719B1=2

ifeq ($(MDU), CYBT423028)
C_FLAGS += -DMDU=CYBT423028
else
ifeq ($(MDU), CY20719B1)
C_FLAGS += -DMDU=CY20719B1
endif
endif

########################################################################
################ DO NOT MODIFY FILE BELOW THIS LINE ####################
########################################################################

