/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's SDP database.
 *
 */

// Zenitron_BT_AMP_sdp_db.h

#ifndef __SDP_DATABASE_H__
#define __SDP_DATABASE_H__

#ifdef USE_AVRCP_CTRLR
#define HANDLE_ATTR_SEQ                         198
#else
#define HANDLE_ATTR_SEQ                         79
#endif
// SDP Record for A2DP Sink
#define HDLR_A2DP_SINK                        0x10001
// SDP Record handle for AVDT Sink
#define HANDLE_AVDT_SINK                        0x10001
// SDP Record handle for AVRC TARGET
#define HANDLE_AVRC_TARGET                      0x10002
// SDP Record handle for AVRC TARGET
#define HANDLE_AVRC_CONTROLLER                  0x10003
// SDP Record handle for SPP
#define HANDLE_SPP                              0x10004

// External definitions
extern const uint8_t  sdp_database[];
extern const uint16_t sdp_database_len;

#endif /* __SDP_DATABASE_H__ */
